### PR TITLE
Release 6.5.1

### LINKED ISSUE #50: Lack of error handling in stream.read
Related to ssb-tunnel, I got this error:

```
/root/ssb-room/node_modules/muxrpc/stream.js:57
        var name = data.name
                        ^

TypeError: Cannot read property 'name' of null
    at PacketStreamSubstream.stream.read (/root/ssb-room/node_modules/muxrpc/stream.js:57:25)
    at PacketStream._onstream (/root/ssb-room/node_modules/packet-stream/index.js:224:13)
    at PacketStream.write (/root/ssb-room/node_modules/packet-stream/index.js:135:41)
    at /root/ssb-room/node_modules/muxrpc/pull-weird.js:56:15
    at /root/ssb-room/node_modules/pull-stream/sinks/drain.js:24:37
    at /root/ssb-room/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/root/ssb-room/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/root/ssb-room/node_modules/pull-reader/index.js:39:14)
    at more (/root/ssb-room/node_modules/pull-reader/index.js:55:13)
    at /root/ssb-room/node_modules/pull-reader/index.js:66:9
```

It's at this line: https://github.com/ssbc/muxrpc/blob/210fac6827b5192a62599401acb55a9e78da0542/stream.js#L56-L67

I think the `end` case should be checked before using `data`, but the first line assumes that `data` exists. I think the error handling hasn't felt 'necessary' so far, but ssb-tunnel is unconventional enough that it might hit more corner cases.

### PR DESCRIPTION
**Pull request by staltz**
Do y'all maintainers agree that this is a patch? (`6.5.0 => 6.5.1`)

The changes made since 6.5.0:

- Tidy and remove unused variables https://github.com/ssb-js/muxrpc/commit/767cf54d66107928055a0f89cd5628b3989903cc 
- Merge branch 'main' into v7 https://github.com/ssb-js/muxrpc/commit/1443aa62a3e0f2d361725a14837c588ed0473470
- Handle `end` case in stream.read (fixes #50) https://github.com/ssb-js/muxrpc/commit/8b12fe739659dc6302924bd36869d80d0722d80c

### CODE REVIEW

**Comment by arj03** [comment]
Yes

**Review by christianbundy — APPROVED** [review]

**Review by soapdog — APPROVED** [review]

**Comment by soapdog** [comment]
I was going to merge this request already but to be honest I don't know how the release to npm works, is it automatic? is there a CI doing it? I'm afraid of merging it and being out of sync with npm.

**Comment by staltz** [comment]
@soapdog I'll do the release after merging, nothing happens automatically. Or you can do the release, this is just to open a discussion about the version change.

**Comment by staltz** [comment]
Released `muxrpc@6.5.1`

**Pull request merged**
